![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [2]:
my_array = np.arange(10)
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
print(my_array)
print(my_array[-2:-4:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
print(my_array[-8::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [7]:
ejer4_1 = np.arange(1,21).reshape(4,5)

In [10]:
ejer4_1.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [12]:
print(ejer4_1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [26]:
np.array([ejer4_1[0][0:2] ,ejer4_1[1][0:2]])

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [31]:
np.array([ejer4_1[0][0:5:2] ,ejer4_1[2][0:5:2]])

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [35]:
np.array([ejer4_1[0][::-1], ejer4_1[1][::-1], ejer4_1[2][::-1]])

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [37]:
np.array([np.flip(ejer4_1[0]), np.flip(ejer4_1[1]), np.flip(ejer4_1[2])])

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [45]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [46]:
mask8 = np.array(x == "Loro")
print(mask8)
print(x[mask8])

[ True False False  True False]
['Loro' 'Loro']


In [52]:
print(x[[True, False, False, True, False]])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [28]:
[np.random.randint(5, size = (5,3)) for i in range(4)]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [54]:
np.flip(ejer4_1)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [65]:
ejer10 = np.full((10,1), 0, dtype=np.int32)
#print(ejer10)
print(ejer10.nbytes)

ejer10[3] = 1

print(ejer10)

40
[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [66]:
ejer12 = np.arange(10,50)
print(ejer12)

print(np.flip(ejer12))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [69]:
ejer13 = np.array([1,2,0,0,4,0])

np.where(ejer13 != 0)


(array([0, 1, 4], dtype=int64),)

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [74]:
ejer14 = np.random.randint(99, size=(10,10))
print(ejer14)
print(ejer14.min())
print(ejer14.max())

[[67  1 71 49 43  7 56 35 34 96]
 [53 62 32 54 31 95 30 81 53  2]
 [ 2 78 65 44 45 53 64  7 92 10]
 [60 96 41 41 47 70 59 56  7 60]
 [90 76 59 64 27 40 37 18 33 86]
 [19 73 65 27 51 57 47 80 60  8]
 [54 23 69 64 15 39 90 76 10 30]
 [39 87 89 41 66 90 19 35 54 72]
 [ 3 66 49 25 26 12 93 78 55 59]
 [ 5 35 75 24 58 32 67 51 56 33]]
1
96


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [79]:
ejer15 = np.random.randint(99, size=(30))
print(ejer15)
print(ejer15.mean())

[53 50 26 29 29 20 47  3 31  2 40 45  4 11 31  3 86  1 18 48  1  9 26 81
 34 59 42 19 50 78]
32.53333333333333


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [86]:
ejer16 = np.ones((5,5))
for i in range(5):
    
    if i == 0 or i == 4:
        pass
    else:
        for j in range(5):
            if j == 0  or j == 4:
                pass
            else:
                ejer16[i][j] = 0

ejer16

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [89]:
ceroUnos = np.array([0, 1, 0, 1, 0, 1, 0, 1])

ejer17 = np.array([ceroUnos, np.flip(ceroUnos),ceroUnos, np.flip(ceroUnos),ceroUnos, np.flip(ceroUnos),ceroUnos, np.flip(ceroUnos)])
print(ejer17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [96]:
ceroUnos = np.array([[0,1], [1,0]])
np.tile(ceroUnos,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [100]:
ejer19 = np.random.randint(99, size = (5,5))
(ejer19 - np.mean(ejer19))/np.std(ejer19)

array([[-1.41943361, -0.3966976 ,  0.7190144 ,  1.24587841, -0.5516576 ],
       [-1.14050561,  0.9049664 , -1.51240961, -0.0867776 , -1.45042561],
       [-1.41943361,  1.0289344 , -1.23348161, -1.45042561,  0.4090944 ],
       [ 0.4400864 , -0.2727296 ,  0.8119904 ,  0.5640544 ,  1.43183041],
       [ 0.5330624 ,  0.9979424 ,  0.6880224 , -0.2417376 ,  1.40083841]])

[[20 24  8  1 28]
 [29  2  1 26 14]
 [ 9 10 29 28  5]
 [29 14 16 11 27]
 [10  5 21 19 10]]
[[18  2 22 11 11]
 [10 22 28  8 23]
 [26 10 13 23 19]
 [29  4 20  4 21]
 [ 1  3  6 20 13]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [1]:
import numpy as np

In [12]:
ejer20 = np.arange(10)

ejer20 = np.where((ejer20 > 3) & (ejer20 < 8),-1,ejer20)
ejer20

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9])

In [13]:
ejer20 = np.where((ejer20 > 3) & (ejer20 < 8),-ejer20,ejer20)
ejer20

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [21]:
tablero = np.full((10,10),' ')

#Posicionamos primer barco
tablero[0][1] = "O"
tablero[1][1] = "O"

#Posicionamos segundo barco
tablero[1][3] = "O"
tablero[1][4] = "O"
tablero[1][5] = "O"
tablero[1][6] = "O"


#Disparo a barco
tablero[0][1] = "X"

#Disparo al agua
tablero[2][1] = "-"

print(tablero)

[[' ' 'X' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' '-' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' '-' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '-' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' '-' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


4
5


[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'O' ' ' '-' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' '-' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


S


[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'O' ' ' '-' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'O' ' ' ' ' ' ' ' ']
 [' ' ' ' '-' ' ' ' ' 'O' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'O' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
